name: QEMU

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: install packages
        run: |
          sudo apt-get update --quiet || true
          sudo apt-get install -y wget qemu-system-x86 qemu-utils openssh-client netcat-openbsd

      - name: Download latest FreeBSD VM image
        run: |
          LATEST_RELEASE=$(curl -s https://download.freebsd.org/ftp/releases/VM-IMAGES/ | grep -Eo 'href="[0-9]+\.[0-9]+-RELEASE/' | sort -V | tail -1 | cut -d'"' -f2)
          IMG_PAGE="https://download.freebsd.org/ftp/releases/VM-IMAGES/${LATEST_RELEASE}amd64/Latest/"
          IMG_FILE=$(curl -s "$IMG_PAGE" | grep -Eo 'FreeBSD-[0-9.]+-RELEASE-amd64.qcow2.xz' | head -1)
          FULL_URL="${IMG_PAGE}${IMG_FILE}"
          wget -O freebsd.qcow2.xz "$FULL_URL"
          xz -d freebsd.qcow2.xz

      - name: Start FreeBSD VM (background)
        run: |
          nohup qemu-system-x86_64 \
            -m 2048 \
            -cpu host \
            -drive file=freebsd.qcow2,format=qcow2 \
            -net user,hostfwd=tcp::2222-:22 \
            -net nic \
            -nographic &
          sleep 60

      - name: Wait for SSH (VM boot)
        run: |
          for i in {1..60}; do
            nc -z localhost 2222 && break
            sleep 5
          done

      - name: Clone repo in VM and build
        run: |
          ssh -o StrictHostKeyChecking=no -p 2222 freebsd@localhost "git clone https://github.com/${{ github.repository }} oca && cd oca && mkimage"
